"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const logger_1 = require("./logger");
logger_1.default.log("Testing!");
logger_1.default.log({ a: "Testing!" });
logger_1.default.warning("Testing!");
logger_1.default.warning({ a: "Testing!" });
logger_1.default.error("Testing!");
logger_1.default.error({ a: "Testing!" });
logger_1.default.debug("Testing!");
logger_1.default.debug({ a: "Testing!" });
